{{ config(materialized='table',
    database='staging',
   pre_hook=[
        "
         INSERT INTO STAGING.DIMENSIONS.DIM_COUNTRY(COUNTRYNAME)
        select distinct CUSTOMEVENTS.COUNTRY
        from RAW.PRIVATE_EVENTS.CUSTOM_EVENTS CUSTOMEVENTS
        left join STAGING.DIMENSIONS.DIM_COUNTRY dimcountry
            on COALESCE(NULLIF(CUSTOMEVENTS.COUNTRY, ''), 'Not Defined') = dimcountry.COUNTRYNAME
        where dimcountry.COUNTRYNAME IS NULL
        ",
         "
         INSERT INTO STAGING.DIMENSIONS.DIM_REGION(REGIONNAME, COUNTRYID)
        select distinct CUSTOMEVENTS.REGION, dimcountry.COUNTRYID
        from RAW.PRIVATE_EVENTS.CUSTOM_EVENTS CUSTOMEVENTS
        inner join STAGING.DIMENSIONS.DIM_COUNTRY dimcountry
            on COALESCE(NULLIF(CUSTOMEVENTS.COUNTRY, ''), 'Not Defined') = dimcountry.COUNTRYNAME
        left join STAGING.DIMENSIONS.DIM_REGION dimregion
            on COALESCE(NULLIF(CUSTOMEVENTS.REGION, ''), 'Not Defined') = dimregion.REGIONNAME
        where dimregion.REGIONNAME IS NULL
        ",
        "
         INSERT INTO STAGING.DIMENSIONS.DIM_CITY(CITYNAME, COUNTRYID, REGIONID)
        select distinct CUSTOMEVENTS.CITY, dimcountry.COUNTRYID, dimregion.REGIONID
        from RAW.PRIVATE_EVENTS.CUSTOM_EVENTS CUSTOMEVENTS
        inner join STAGING.DIMENSIONS.DIM_COUNTRY dimcountry
            on COALESCE(NULLIF(CUSTOMEVENTS.COUNTRY, ''), 'Not Defined') = dimcountry.COUNTRYNAME
        inner join STAGING.DIMENSIONS.DIM_REGION dimregion
            on COALESCE(NULLIF(CUSTOMEVENTS.REGION, ''), 'Not Defined') = dimregion.REGIONNAME
        left join STAGING.DIMENSIONS.DIM_CITY dimcity
            on COALESCE(NULLIF(CUSTOMEVENTS.CITY, ''), 'Not Defined') = dimcity.CITYNAME
        where dimcity.CITYNAME IS NULL
        "
        ]
   )

  }}



       SELECT DISTINCT
            CUSTOM_EVENTS.CUSTOMEVENTID,
            IFF(CUSTOM_EVENTS.LASTSEARCHID = '', NULL, CUSTOM_EVENTS.LASTSEARCHID) AS LASTSEARCHID,
            CUSTOM_EVENTS.DATETIME,
            INITCAP(IFF(CUSTOM_EVENTS.USERAGENT = '', NULL, CUSTOM_EVENTS.USERAGENT)) AS USERAGENT,
            CUSTOM_EVENTS.ISINTERNAL,
            INITCAP(IFF(CUSTOM_EVENTS.OPERATINGSYSTEMWITHVERSION = '', NULL, CUSTOM_EVENTS.OPERATINGSYSTEMWITHVERSION)) AS OPERATINGSYSTEMWITHVERSION,
            DIMCOUNTRY.COUNTRYID,
            DIMCITY.CITYID,
            INITCAP(IFF(CUSTOM_EVENTS.LANGUAGE = '', NULL, CUSTOM_EVENTS.LANGUAGE)) AS LANGUAGE,
            INITCAP(IFF(CUSTOM_EVENTS.BROWSERWITHVERSION = '', NULL, CUSTOM_EVENTS.BROWSERWITHVERSION)) AS BROWSERWITHVERSION,
            IFF(CUSTOM_EVENTS.USERNAME = '', NULL, CUSTOM_EVENTS.USERNAME) AS USERNAME,
            CUSTOM_EVENTS.ANONYMOUS,
            INITCAP(IFF(CUSTOM_EVENTS.BROWSER = '', NULL, CUSTOM_EVENTS.BROWSER)) AS BROWSER,
            IFF(CUSTOM_EVENTS.USERID = '', NULL, CUSTOM_EVENTS.USERID) AS USERID,
            INITCAP(IFF(CUSTOM_EVENTS.ORIGINCONTEXT = '', NULL, CUSTOM_EVENTS.ORIGINCONTEXT)) AS ORIGINCONTEXT,
            IFF(CUSTOM_EVENTS.ORIGINLEVEL3 = '', NULL, CUSTOM_EVENTS.ORIGINLEVEL3) AS ORIGINLEVEL3,
            INITCAP(IFF(CUSTOM_EVENTS.DEVICECATEGORY = '', NULL, CUSTOM_EVENTS.DEVICECATEGORY)) AS DEVICECATEGORY,
            INITCAP(IFF(CUSTOM_EVENTS.ORIGINLEVEL1 = '', NULL, CUSTOM_EVENTS.ORIGINLEVEL1)) AS ORIGINLEVEL1,
            INITCAP(IFF(CUSTOM_EVENTS.ORIGINLEVEL2 = '', NULL, CUSTOM_EVENTS.ORIGINLEVEL2)) AS ORIGINLEVEL2,
            DIMREGION.REGIONID,
            INITCAP(IFF(CUSTOM_EVENTS.EVENTVALUE = '', NULL, CUSTOM_EVENTS.EVENTVALUE)) AS EVENTVALUE,
            INITCAP(IFF(PARSE_JSON(CUSTOM_EVENTS.CUSTOMDATAS::VARIANT):c_toto = '', NULL, PARSE_JSON(CUSTOM_EVENTS.CUSTOMDATAS::VARIANT):c_toto)) AS c_toto,
            INITCAP(IFF(PARSE_JSON(CUSTOM_EVENTS.CUSTOMDATAS::VARIANT):c_coveo = '', NULL, PARSE_JSON(CUSTOM_EVENTS.CUSTOMDATAS::VARIANT):c_coveo)) AS c_coveo,
            INITCAP(IFF(CUSTOM_EVENTS.EVENTTYPE = '', NULL, CUSTOM_EVENTS.EVENTTYPE)) AS EVENTTYPE,
            CUSTOM_EVENTS.VISITORID,
            INITCAP(IFF(CUSTOM_EVENTS.CUSTOMEVENTORIGINLEVEL1 = '', NULL, CUSTOM_EVENTS.CUSTOMEVENTORIGINLEVEL1)) AS CUSTOMEVENTORIGINLEVEL1,
            INITCAP(IFF(CUSTOM_EVENTS.CUSTOMEVENTORIGINLEVEL2 = '', NULL, CUSTOM_EVENTS.CUSTOMEVENTORIGINLEVEL2)) AS CUSTOMEVENTORIGINLEVEL2,
            CUSTOM_EVENTS.MOBILE,
            CUSTOM_EVENTS.VISITID,
            INITCAP(IFF(CUSTOM_EVENTS.C_JSUIVERSION = '', NULL, CUSTOM_EVENTS.C_JSUIVERSION)) AS C_JSUIVERSION,
            CURRENT_TIMESTAMP() AS INSERTION_DATETIME

    FROM RAW.PRIVATE_EVENTS.CUSTOM_EVENTS  CUSTOM_EVENTS
    INNER JOIN STAGING.DIMENSIONS.DIM_COUNTRY DIMCOUNTRY
        ON COALESCE(NULLIF(CUSTOM_EVENTS.COUNTRY, ''), 'Not Defined') = DIMCOUNTRY.COUNTRYNAME

    INNER JOIN STAGING.DIMENSIONS.DIM_REGION DIMREGION
        ON COALESCE(NULLIF(CUSTOM_EVENTS.REGION, ''), 'Not Defined') = DIMREGION.REGIONNAME

    INNER JOIN STAGING.DIMENSIONS.DIM_CITY DIMCITY
        ON COALESCE(NULLIF(CUSTOM_EVENTS.CITY, ''), 'Not Defined') = DIMCITY.CITYNAME
