{{ config(materialized='table',
    database='staging',
    pre_hook=[
        "
         INSERT INTO STAGING.DIMENSIONS.DIM_COUNTRY(COUNTRYNAME)
        select distinct SEARCHES.COUNTRY
        from RAW.PRIVATE_EVENTS.SEARCHES SEARCHES
        left join STAGING.DIMENSIONS.DIM_COUNTRY dimcountry
            on COALESCE(NULLIF(SEARCHES.COUNTRY, ''), 'Not Defined') = dimcountry.COUNTRYNAME
        where dimcountry.COUNTRYNAME IS NULL
        ",
         "
         INSERT INTO STAGING.DIMENSIONS.DIM_REGION(REGIONNAME, COUNTRYID)
        select distinct SEARCHES.REGION, dimcountry.COUNTRYID
        from RAW.PRIVATE_EVENTS.SEARCHES SEARCHES
        inner join STAGING.DIMENSIONS.DIM_COUNTRY dimcountry
            on COALESCE(NULLIF(SEARCHES.COUNTRY, ''), 'Not Defined') = dimcountry.COUNTRYNAME
        left join STAGING.DIMENSIONS.DIM_REGION dimregion
            on COALESCE(NULLIF(SEARCHES.REGION, ''), 'Not Defined') = dimregion.REGIONNAME
        where dimregion.REGIONNAME IS NULL
        ",
        "
         INSERT INTO STAGING.DIMENSIONS.DIM_CITY(CITYNAME, COUNTRYID, REGIONID)
        select distinct SEARCHES.CITY, dimcountry.COUNTRYID, dimregion.REGIONID
        from RAW.PRIVATE_EVENTS.SEARCHES SEARCHES
        inner join STAGING.DIMENSIONS.DIM_COUNTRY dimcountry
            on COALESCE(NULLIF(SEARCHES.COUNTRY, ''), 'Not Defined') = dimcountry.COUNTRYNAME
        inner join STAGING.DIMENSIONS.DIM_REGION dimregion
            on COALESCE(NULLIF(SEARCHES.REGION, ''), 'Not Defined') = dimregion.REGIONNAME
        left join STAGING.DIMENSIONS.DIM_CITY dimcity
            on COALESCE(NULLIF(SEARCHES.CITY, ''), 'Not Defined') = dimcity.CITYNAME
        where dimcity.CITYNAME IS NULL
        "
        ]
   )

  }}


   SELECT DISTINCT
            SEARCHES.ID AS SEARCHID,
            SEARCHES.DATETIME,
            INITCAP(IFF(SEARCHES.USERAGENT = '', NULL, SEARCHES.USERAGENT)) AS USERAGENT,
            SEARCHES.SEARCHISCONTEXTUAL,
            SEARCHES.ISINTERNAL,
            INITCAP(IFF(SEARCHES.ACTIONCAUSE = '', NULL, SEARCHES.ACTIONCAUSE)) AS ACTIONCAUSE,
            INITCAP(IFF(SEARCHES.OPERATINGSYSTEMWITHVERSION = '', NULL, SEARCHES.OPERATINGSYSTEMWITHVERSION)) AS OPERATINGSYSTEMWITHVERSION,
            DIMCOUNTRY.COUNTRYID,
            DIMCITY.CITYID,
            SEARCHES.BATCHID,
            INITCAP(IFF(SEARCHES.LANGUAGE = '', NULL, SEARCHES.LANGUAGE)) AS LANGUAGE,
            INITCAP(IFF(SEARCHES.BROWSERWITHVERSION = '', NULL, SEARCHES.BROWSERWITHVERSION)) AS BROWSERWITHVERSION,
            IFF(SEARCHES.USERNAME = '', NULL, SEARCHES.USERNAME) AS USERNAME,
            CAST(SEARCHES.NUMBEROFRESULTS AS INTEGER) AS NUMBEROFRESULTS,
            INITCAP(IFF(SEARCHES.SPLITTESTRUNVERSION = '', NULL, SEARCHES.SPLITTESTRUNVERSION)) AS SPLITTESTRUNVERSION,
            SEARCHES.ANONYMOUS,
            INITCAP(IFF(SEARCHES.BROWSER = '', NULL, SEARCHES.BROWSER)) AS BROWSER,
            SEARCHES.RESPONSETIMEMS,
            INITCAP(IFF(PARSE_JSON(SEARCHES.CUSTOMDATAS::VARIANT):c_recommendation::VARCHAR = '', NULL, PARSE_JSON(SEARCHES.CUSTOMDATAS::VARIANT):c_recommendation::VARCHAR)) AS C_RECOMMENDATION,
            INITCAP(IFF(PARSE_JSON(SEARCHES.CUSTOMDATAS::VARIANT):c_inputtitle::VARCHAR = '', NULL, PARSE_JSON(SEARCHES.CUSTOMDATAS::VARIANT):c_inputtitle::VARCHAR)) AS C_INPUTTITLE,
            INITCAP(IFF(PARSE_JSON(SEARCHES.CUSTOMDATAS::VARIANT):c_customvalue::VARCHAR = '', NULL, PARSE_JSON(SEARCHES.CUSTOMDATAS::VARIANT):c_customvalue::VARCHAR)) AS C_CUSTOMVALUE,
            INITCAP(IFF(PARSE_JSON(SEARCHES.CUSTOMDATAS::VARIANT):c_partnerstype::VARCHAR = '', NULL, PARSE_JSON(SEARCHES.CUSTOMDATAS::VARIANT):c_partnerstype::VARCHAR)) AS C_PARTNERSTYPE,
            INITCAP(IFF(PARSE_JSON(SEARCHES.CUSTOMDATAS::VARIANT):c_partners::VARCHAR = '', NULL, PARSE_JSON(SEARCHES.CUSTOMDATAS::VARIANT):c_partners::VARCHAR)) AS C_PARTNERS,
            IFF(PARSE_JSON(SEARCHES.CUSTOMDATAS::VARIANT):c_ipaddress::VARCHAR = '', NULL, PARSE_JSON(SEARCHES.CUSTOMDATAS::VARIANT):c_ipaddress::VARCHAR) AS C_IPADDRESS,
            INITCAP(IFF(SEARCHES.SEARCHORIGINLEVEL1 = '', NULL, SEARCHES.SEARCHORIGINLEVEL1)) AS SEARCHORIGINLEVEL1,
            INITCAP(IFF(SEARCHES.SEARCHORIGINLEVEL2 = '', NULL, SEARCHES.SEARCHORIGINLEVEL2)) AS SEARCHORIGINLEVEL2,
            SEARCHES.WITHRESULTS,
            IFF(SEARCHES.USERID = '', NULL, SEARCHES.USERID) AS USERID,
            INITCAP(IFF(SEARCHES.ORIGINCONTEXT = '', NULL, SEARCHES.ORIGINCONTEXT)) AS ORIGINCONTEXT,
            IFF(SEARCHES.ORIGINLEVEL3 = '', NULL, SEARCHES.ORIGINLEVEL3) AS ORIGINLEVEL3,
            INITCAP(IFF(SEARCHES.CAUSEV2 = '', NULL, SEARCHES.CAUSEV2)) AS CAUSEV2,
            INITCAP(IFF(SEARCHES.QUERYPIPELINE = '', NULL, SEARCHES.QUERYPIPELINE)) AS QUERYPIPELINE,
            INITCAP(IFF(SEARCHES.DEVICECATEGORY = '', NULL, SEARCHES.DEVICECATEGORY)) AS DEVICECATEGORY,
            INITCAP(IFF(SEARCHES.ORIGINLEVEL1 = '', NULL, SEARCHES.ORIGINLEVEL1)) AS ORIGINLEVEL1,
            INITCAP(IFF(SEARCHES.ORIGINLEVEL2 = '', NULL, SEARCHES.ORIGINLEVEL2)) AS ORIGINLEVEL2,
            DIMREGION.REGIONID,
            INITCAP(IFF(SEARCHES.SPLITTESTRUNNAME = '', NULL, SEARCHES.SPLITTESTRUNNAME)) AS SPLITTESTRUNNAME,
            IFF(SEARCHES.ADVANCEDQUERYEXPRESSION = '', NULL, SEARCHES.ADVANCEDQUERYEXPRESSION) AS ADVANCEDQUERYEXPRESSION,
            SEARCHES.VISITORID,
            INITCAP(IFF(SEARCHES.QUERYEXPRESSION = '', NULL, SEARCHES.QUERYEXPRESSION)) AS QUERYEXPRESSION,
            WITHCLICKS,
            MOBILE,
            SEARCHES.VISITID,
            INITCAP(IFF(SEARCHES.C_JSUIVERSION = '', NULL, SEARCHES.C_JSUIVERSION)) AS C_JSUIVERSION,
            INITCAP(IFF(SEARCHES.C_PRODUCT = '', NULL, SEARCHES.C_PRODUCT)) AS C_PRODUCT,
            INITCAP(IFF(SEARCHES.C_FACETVALUE = '', NULL, SEARCHES.C_FACETVALUE)) AS C_FACETVALUE,
            CURRENT_TIMESTAMP() AS INSERTION_DATETIME

   FROM RAW.PRIVATE_EVENTS.SEARCHES SEARCHES
   INNER JOIN STAGING.DIMENSIONS.DIM_COUNTRY DIMCOUNTRY
        ON COALESCE(NULLIF(SEARCHES.COUNTRY, ''), 'Not Defined') = DIMCOUNTRY.COUNTRYNAME

    INNER JOIN STAGING.DIMENSIONS.DIM_REGION DIMREGION
        ON COALESCE(NULLIF(SEARCHES.REGION, ''), 'Not Defined') = DIMREGION.REGIONNAME

    INNER JOIN STAGING.DIMENSIONS.DIM_CITY DIMCITY
        ON COALESCE(NULLIF(SEARCHES.CITY, ''), 'Not Defined') = DIMCITY.CITYNAME
