{{ config(
    materialized='table',
    database='staging',
    )

  }}

    SELECT DISTINCT
          GROUPS.SEARCHID,
          GROUPS.DATETIME,
          INITCAP(IFF(GROUPS.GROUPNAME = '', NULL, GROUPS.GROUPNAME)) AS GROUPNAME,
          CURRENT_TIMESTAMP() AS INSERTION_DATETIME
    FROM RAW.PRIVATE_EVENTS.GROUPS GROUPS

