{{ config(
    materialized='table',
    database='staging',
     pre_hook=["
        INSERT INTO STAGING.DIMENSIONS.DIM_DOCUMENTAUTHOR(AUTHORNAME)
        select distinct CLICKS.DOCUMENTAUTHOR
        from RAW.PRIVATE_EVENTS.CLICKS CLICKS
        left join STAGING.DIMENSIONS.DIM_DOCUMENTAUTHOR DOCAUTH
            on COALESCE(NULLIF(CLICKS.DOCUMENTAUTHOR, ''), 'Not Defined')  = DOCAUTH.AUTHORNAME
        where DOCAUTH.AUTHORNAME IS NULL
        ",
        "
         INSERT INTO STAGING.DIMENSIONS.DIM_COUNTRY(COUNTRYNAME)
        select distinct CLICKS.COUNTRY
        from RAW.PRIVATE_EVENTS.CLICKS CLICKS
        left join STAGING.DIMENSIONS.DIM_COUNTRY dimcountry
            on COALESCE(NULLIF(CLICKS.COUNTRY, ''), 'Not Defined') = dimcountry.COUNTRYNAME
        where dimcountry.COUNTRYNAME IS NULL
        ",
         "
         INSERT INTO STAGING.DIMENSIONS.DIM_REGION(REGIONNAME, COUNTRYID)
        select distinct CLICKS.REGION, dimcountry.COUNTRYID
        from RAW.PRIVATE_EVENTS.CLICKS CLICKS
        inner join STAGING.DIMENSIONS.DIM_COUNTRY dimcountry
            on COALESCE(NULLIF(CLICKS.COUNTRY, ''), 'Not Defined') = dimcountry.COUNTRYNAME
        left join STAGING.DIMENSIONS.DIM_REGION dimregion
            on COALESCE(NULLIF(CLICKS.REGION, ''), 'Not Defined') = dimregion.REGIONNAME
        where dimregion.REGIONNAME IS NULL
        ",
        "
         INSERT INTO STAGING.DIMENSIONS.DIM_CITY(CITYNAME, COUNTRYID, REGIONID)
        select distinct CLICKS.CITY, dimcountry.COUNTRYID, dimregion.REGIONID
        from RAW.PRIVATE_EVENTS.CLICKS CLICKS
        inner join STAGING.DIMENSIONS.DIM_COUNTRY dimcountry
            on COALESCE(NULLIF(CLICKS.COUNTRY, ''), 'Not Defined') = dimcountry.COUNTRYNAME
        inner join STAGING.DIMENSIONS.DIM_REGION dimregion
            on COALESCE(NULLIF(CLICKS.REGION, ''), 'Not Defined') = dimregion.REGIONNAME
        left join STAGING.DIMENSIONS.DIM_CITY dimcity
            on COALESCE(NULLIF(CLICKS.CITY, ''), 'Not Defined') = dimcity.CITYNAME
        where dimcity.CITYNAME IS NULL
        "
        ]
   )

  }}

    SELECT DISTINCT
            CLICKS.CLICKID,
            CLICKS.SEARCHID,
            CLICKS.DATETIME,
            INITCAP(IFF(CLICKS.USERAGENT = '', NULL, CLICKS.USERAGENT)) AS USERAGENT,
            CLICKS.ISINTERNAL,
            INITCAP(IFF(CLICKS.OPERATINGSYSTEMWITHVERSION = '', NULL, CLICKS.OPERATINGSYSTEMWITHVERSION)) AS OPERATINGSYSTEMWITHVERSION,
            DIMCOUNTRY.COUNTRYID,
            DIMCITY.CITYID,
            INITCAP(IFF(CLICKS.LANGUAGE = '', NULL, CLICKS.LANGUAGE)) AS LANGUAGE,
            INITCAP(IFF(CLICKS.BROWSERWITHVERSION = '', NULL, CLICKS.BROWSERWITHVERSION)) AS BROWSERWITHVERSION,
            IFF(CLICKS.USERNAME = '', NULL, CLICKS.USERNAME) AS USERNAME,
            CLICKS.CLICKRANK,
            CLICKS.ANONYMOUS,
            DOCAUTH.AUTHORID AS DOCAUTHORID,
            INITCAP(IFF(CLICKS.BROWSER = '', NULL, CLICKS.BROWSER)) AS BROWSER,
            CLICKS.SYSTEMURIHASH,
            CLICKS.DOCUMENTURL,
            IFF(CLICKS.USERID = '', NULL,  CLICKS.USERID) AS USERID,
            INITCAP(IFF(CLICKS.CAUSEV2 = '', NULL, CLICKS.CAUSEV2)) AS CAUSEV2,
            INITCAP(IFF(CLICKS.QUERYPIPELINE = '', NULL, CLICKS.QUERYPIPELINE)) AS QUERYPIPELINE,
            INITCAP(IFF(CLICKS.DEVICECATEGORY = '', NULL, CLICKS.DEVICECATEGORY)) AS DEVICECATEGORY,
            INITCAP(IFF(CLICKS.ORIGINLEVEL1 = '', NULL, CLICKS.ORIGINLEVEL1)) AS ORIGINLEVEL1,
            INITCAP(IFF(CLICKS.SOURCENAME = '', NULL, CLICKS.SOURCENAME)) AS SOURCENAME,
            DIMREGION.REGIONID,
            INITCAP(IFF(CLICKS.CLICKORIGINLEVEL1 = '', NULL, CLICKS.CLICKORIGINLEVEL1)) AS CLICKORIGINLEVEL1,
            INITCAP(IFF(PARSE_JSON(CLICKS.CUSTOMDATAS::VARIANT):c_recommendation::VARCHAR = '', NULL, PARSE_JSON(CLICKS.CUSTOMDATAS::VARIANT):c_recommendation::VARCHAR)) AS C_RECOMMENDATION,
            INITCAP(IFF(PARSE_JSON(CLICKS.CUSTOMDATAS::VARIANT):c_jsuiversion::VARCHAR = '', NULL, PARSE_JSON(CLICKS.CUSTOMDATAS::VARIANT):c_jsuiversion::VARCHAR)) AS C_JSUIVERSION,
            INITCAP(IFF(PARSE_JSON(CLICKS.CUSTOMDATAS::VARIANT):c_customvalue::VARCHAR = '', NULL, PARSE_JSON(CLICKS.CUSTOMDATAS::VARIANT):c_customvalue::VARCHAR)) AS C_CUSTOMVALUE,
            INITCAP(IFF(PARSE_JSON(CLICKS.CUSTOMDATAS::VARIANT):c_partnerstype::VARCHAR = '', NULL, PARSE_JSON(CLICKS.CUSTOMDATAS::VARIANT):c_partnerstype::VARCHAR)) AS C_PARTNERSTYPE,
            INITCAP(IFF(PARSE_JSON(CLICKS.CUSTOMDATAS::VARIANT):c_product::VARCHAR = '', NULL, PARSE_JSON(CLICKS.CUSTOMDATAS::VARIANT):c_product::VARCHAR)) AS C_PRODUCT,
            INITCAP(IFF(PARSE_JSON(CLICKS.CUSTOMDATAS::VARIANT):c_partners::VARCHAR = '', NULL, PARSE_JSON(CLICKS.CUSTOMDATAS::VARIANT):c_partners::VARCHAR)) AS C_PARTNERS,
            INITCAP(IFF(PARSE_JSON(CLICKS.CUSTOMDATAS::VARIANT):c_entitlement::VARCHAR = '', NULL, PARSE_JSON(CLICKS.CUSTOMDATAS::VARIANT):c_entitlement::VARCHAR)) AS C_ENTITLEMENT,
            IFF(PARSE_JSON(CLICKS.CUSTOMDATAS::VARIANT):c_ipaddress::VARCHAR = '', NULL, PARSE_JSON(CLICKS.CUSTOMDATAS::VARIANT):c_ipaddress::VARCHAR) AS C_IPADDRESS,
            INITCAP(IFF(CLICKS.COLLECTIONNAME = '', NULL, CLICKS.COLLECTIONNAME)) AS COLLECTIONNAME,
            CLICKS.VISITORID,
            CLICKS.MOBILE,
            INITCAP(IFF(CLICKS.DOCUMENTTITLE = '', NULL, CLICKS.DOCUMENTTITLE)) AS DOCUMENTTITLE,
            CLICKS.VISITID,
            INITCAP(IFF(CLICKS.CLICKCAUSE = '', NULL, CLICKS.CLICKCAUSE)) AS CLICKCAUSE,
            CURRENT_TIMESTAMP() AS INSERTION_DATETIME

    FROM RAW.PRIVATE_EVENTS.CLICKS CLICKS
    INNER JOIN STAGING.DIMENSIONS.DIM_DOCUMENTAUTHOR DOCAUTH
        ON COALESCE(NULLIF(CLICKS.DOCUMENTAUTHOR, ''), 'Not Defined') = DOCAUTH.AUTHORNAME

    INNER JOIN STAGING.DIMENSIONS.DIM_COUNTRY DIMCOUNTRY
        ON COALESCE(NULLIF(CLICKS.COUNTRY, ''), 'Not Defined') = DIMCOUNTRY.COUNTRYNAME

    INNER JOIN STAGING.DIMENSIONS.DIM_REGION DIMREGION
        ON COALESCE(NULLIF(CLICKS.REGION, ''), 'Not Defined') = DIMREGION.REGIONNAME

    INNER JOIN STAGING.DIMENSIONS.DIM_CITY DIMCITY
        ON COALESCE(NULLIF(CLICKS.CITY, ''), 'Not Defined') = DIMCITY.CITYNAME

